---
title: "Frequently Asked Questions"
output: html_document
---

**Why is there so much discussion about public employee pensions?  What is the controversy?**

State and local governments promise pensions to public employees when they retire.  A pension is a regular paycheck that the employee receives every month from the moment he or she retires, and these payments last for the rest of the employee’s life.  In many cases, this payment covers the employee’s spouse for the entirety of his or her life as well.  This may seem foreign to most private sector readers since these types of benefits are becoming rarer and rarer in the private sector.  However, this arrangement remains extremely common for public employees, including the vast majority of public school teachers and public safety officials such as police officers and firefighters.

The controversy derives from the fact that state and local governments make these promises, but they generally do not set aside enough money to pay for these promises down the road.  If the pensions are underfunded, then future taxpayers will have to pay twice: once for the new, current public employees that will provide them with the services and also for the retirement pensions of the public employees that worked for the city or state in the past. This is increasingly happening now, as pension contributions are among the fastest rising budget items, as states and cities. 

**So how do state and local governments prepare to pay these pensions?**

States set aside money in pension funds, and many states have more than one pension fund.  Typically, the boundaries of these funds are determined by all the employees of one or a few classes of public positions.  For example, the firefighters of a given state may have their own pension fund, the police officers may have another, the teachers their own, and so on and so forth.  Advisors trained in insurance calculation, known as actuaries are then hired to assist in determining how much exactly needs to be set aside to ensure that the pensions of the public employees are funded properly.  However, these actuaries have been using fairly aggressive standards for their assumed rates of return on investment.  Typically, this figure has been about 7.5%. This means that they are effectively assuming the amount of money the city or state sets aside would double every 9 years due to investment returns.

As an example, consider an individual who borrows $100,000 due in ten years at 0% interest. The individual spends half of the funds today on discretionary spending, such as a trip around the world. The remaining $50,000 is placed in a portfolio of stocks and bonds, which historically has had returns of around 7.5%, and these funds are in a dedicated trust to pay off the debt. The individual then goes to a bank to take out a mortgage on his house and is asked to disclose all his assets and liabilities. The actuaries’ concept of expected return discount is equivalent to this individual stating that his net debts are zero, on the grounds that the $50,000 is presumed to double to $100,000 in ten years to pay off the $100,000 debt. Of course, an individual who neglected to disclose this arrangement would have committed ﬁnancial fraud, but a government with $50,000 in assets to pay a $100,000 pension payment in ten years is allowed to declare this promise to be “fully funded.”

**I read that states and cities only contribute about 5% to their total generated revenue to pensions.  Does that mean this can't be a very big problem?**

Consider a situation where your friend told you that the credit card payments he or she was making only amounted to 5% of his income per year; however, as it turned out, the amount of money he or she was spending with his or her credit card actually comprised about 30% of his or her income.  Would the statement that he or she was only spending 5% of his or her income on credit card payments be at all relevant?  This same idea holds true for pension funds.  Merely looking at the current percentage of a state’s budget that is allocated to pension funds indicates absolutely nothing about the financial standing of the fund itself.  It could be that the pension fund needs a far higher revenue allocation to be properly funded and to remain solvent for years to come.

**What exactly do all of the statistics mentioned on the pension map mean?**

After choosing a specific state, county or city on the interactive map, there are several statistics listed – the “Reported Value of Unfunded Liabilities,” the “Market Value of Unfunded Liabilities,” the “Unfunded Liability Per Person,” the “Percent of Own Revenue Contributed,” and finally the “Required Contribution to Maintain the Existing Liability.”

The “Reported Value of Unfunded Liabilities” figure represents what the state is reporting as the amount of money that is additionally necessary in meeting the state’s obligation to its public employees under an assumed rate of return of approximately 7-8%.  The “Market Value of Unfunded Liabilities” figure is the amount of money that is additionally required to meet its obligations when using the virtually “risk-free” assumption of the treasury bond yield of approximately 2-3%.  As an example, consider Nevada. Nevada has 5x billion of unfunded liabilities under their own accounting, and $4 billion when using proper standards of financial measurement.  The “Unfunded Liability Per Person” total uses our metric, the “Market Value of Unfunded Liabilities,” and divides this figure by the population of Nevada.  Ultimately then, using this calculation for 2017, it would require every man, woman and child in Nevada to pay an additional $13,827 to merely fund the current liabilities of its pension system under a safe investment rate of return.  

The final two statistics mentioned focus on state-level revenue contributions.  The “Percent of Own Revenue Contributed” figure represents the current amount of revenue allocated to Nevada’s pension plans, and the “Required Contribution to Maintain the Existing Liability” figure represents the percentage of Nevada’s revenue that would need to be made under the government bond yield assumption.  Ultimately, Nevada would need to contribute 22.95% of its state revenues, as opposed to its current rate of 10.87%, in order to cover its unfunded liability figure under “risk-free” assumptions. 

**Still, historically speaking, the S&P 500 has had an annual average return of around 7.5%.  Why use such a low assume rate of return such as the treasury yield as a benchmark instead?**   

It must be understood that most observers of financial markets today believe a 7.5% compound annualized return is wildly optimistic and unlikely to be achieved.  This has been pointed out by investing luminaries such as Michael Bloomberg and Warren Buffett. While you may assume that stocks in the long run are less risky and are likely to march ever upward, the experiences of other countries suggest that you cannot assume that time will bail out pension systems from the possibility of poor stock returns. For example, the Japanese stock market as represented by the Nikkei 225 rose to a high of 38,916 points at the end of 1989. As of April 2016, the index stands around 18,500, representing a capital loss of 52.5 percent. In addition, finance academics have written extensively about the problem imbedded in attempting to use market statistics to make broad predictions (Pastor and Stambaugh 2012) and the fact that we simply do not have a long enough history of stock returns to know what the true distribution of stock returns really is.  With this in mind, we must remember the importance of being careful and sensible when making these assumptions, as countless public employees are depending on these promises made by politicians and union leaders regarding their pensions and benefits.  These employees are planning their careers and retirements based upon these figures, so therefore, it only makes sense to use a responsible, dependable, and most probable rate of return when making these assumptions.

**Should we not want to provide our public employees with pensions as well as health benefits for their service to their respective communities?  They did, after all, forgo richer opportunities in the private sector.**

Hard working public employees have dedicated their lives toward serving their communities, and therefore it is of the utmost importance that we highlight and right any imprudent financial decisions or structures that may place already promised pensions and health benefits at risk for these employees.  Using safer assumed rates of return is a necessary condition in forcing union leaders and politicians to make wiser, safer promises on behalf of public employees. Creating large unfunded pension promises is to nobody's benefit.

**Well, if this doomsday scenario were to take place and my state had to declare bankruptcy, what would happen?**

There are three ways a state, county or city can address the financial distress that would come about in a bankruptcy: taxes could be raised on the area’s citizens, cuts could be made to the salaries and benefits of the public employees in the pension system, or municipal bond holders could absorb the losses.  However, in many states, pension promises to public employees are ostensibly protected the states’ constitutions.  

Take, for example, the bankruptcy that occurred in 2013 in Detroit, Michigan.  Article 9, § 24 of Michigan’s State Constitution reads as follows, “The accrued financial benefits of each pension plan and retirement system of the state and its political subdivisions shall be a contractual obligation thereof which shall not be diminished or impaired thereby.” Despite this protection, the pension system’s benefits were cut by 4.5% as part of the bankruptcy, which also cost pension recipients inflation adjustments.  Municipal bond holders fared considerably worse.  They only received between 14 and 75 cents on the dollar, depending on the type of bond they held.  Many of these bondholders were under the illusion that municipal bonds were essentially risk free and provided an easy way to shelter their retirement savings from taxes while earning fairly high returns. 

What must be stressed though is the sad reality that still persists in Detroit today:  despite the significant measures that were taken to right the situation at the time, ultimately the structure and accounting principles remain the same and therefore the underlying issues remain the same.  These pension funds are still underfunded and are potentially another failed, risky investment away from collapse. And the same is true if many other cities and states in the United States.

This example also highlights the apparent seniority of pension benefits over municipal bonds in the case of municipal bankruptcy. If pension benefits are vitually guaranteed, their cost to the public (and values to workers) should be measured using the very low yields on very high-grade bonds. 

**To what extent have public sector unions contributed to the unfunded pension liablity figures?**

While all states have public sector unions, not all public sector unions have the same levels of power when it comes to determining the salaries and benefit structures of its employees.  More than half of the states in the United States (28) have adopted "Right to Work" laws.  These laws guarantee that no individual can be forced to join or not join or to pay dues to a labor union as a condition of employment.  While this in and of itself does not eliminate pubic sector unions' ability to collectively bargain, many of these same states have implemented other restrictions and standards on its public sector unions that reduce union leaders' power in determining the salaries and benefits of public employees.  The states that have adopted these laws on average have an unfunded liability per capita figure $5,449 less than those states that do not have any form of these laws.  Generally speaking, the greater the degree of power of the public sector unions in a state, the higher the level of unfunded pension liabilities in that state.   

**If this is the case, why has this issue persisted?  Why haven’t any union leaders or politicians fixed these structural problems?**

Much of this has to do with the perverse incentives that exist for both the union leaders and politicians. From the union leaders’ perspectives their intentions are focused on obtaining promises for the public employees they represent during the collective bargaining process (for the majority of states that allow collective bargaining). If these terms are agreed upon with the states’ politicians, then it is incumbent upon the politicians to make the math work. From the politicians’ perspectives, they would prefer not to be seen as anti-labor or public employee.  In fact, these unions largely hold an inordinate amount of power in the political processes of these states, so capitulating on increasing promises to public employees is the path of least resistance in politicians’ reelection campaigns.

Even in those states that prohibit collective bargaining for public employees such as North Carolina, South Carolina, and Georgia, politicians would prefer to appear in favor of public workers, if possible. Therefore, these states, while having more accessible means to making substantive changes to benefit and salary structures, have almost identical assumed rates of return as those states where collective bargaining is legalized. 

These situations are precisely why these high discount rates have become so attractive to politicians looking to essentially put lipstick on the proverbial pig.  These high discount rates make it appear as if the pension funds are more funded than they are in actuality.  This allows for more money in the states’ budgets to be allocated to other projects and services that are intended for the wider public.  However, as has been mentioned earlier, this structure is unsustainable over time and places public employees’ pensions and benefits at significant risk.  



<style type="text/css">

body{ /* Normal  */
      font-family: Helvetica;
      font-size: 11px;
  }
td {  /* Table  */
  font-size: 8px;
  color: Gray;
}
h1.title {
  font-size: 20px;
  color: Teal;
}
